# Server Configuration
server.port=8080

# Spring Application Name
spring.application.name=AlquilerPlayaWeb

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Database Configuration (Se debe verificar que coincida con ConexionDB o db.properties actual)
# Si reutilizamos ConexionDB.java con su propio properties, esto es redundante pero buena practica para Spring
# Asumiremos la configuracion tipica, pero el codigo DAO usa ConexionDB.java.
# Dejaremos esto aqui para futuro uso o si decidimos inyectar DataSource
# Database Configuration (PostgreSQL - Supabase)
spring.datasource.url=jdbc:postgresql://db.goehhhwusdoduduxntgq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=G+M.*2caUwa?SiS
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.playa.alquiler=DEBUG
